In [1]:
import torch

Basic tensory manipulations. Few ways to create tensores:

In [2]:
z=torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


Created a 5x3 matrix filled with zeros. 32 bit floating point numbers is default PyTorch. You can always override the default. 

In [3]:
i = torch.ones ((5,3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


When we do change the default, tensorFlow helps by reporting the change when printed.

It's common to initialize learning weights randomly, often with a specific seed for the PRNG for reproducibility of results.

Learning weights: Numbers neural networks learn during training. What makes a model "Smart" 

input x weight = output. Large weight, extremely important, weight zero, input ignored. 

In [4]:
torch.manual_seed(1729)
r1 = torch.rand(2, 2)
print ("A random tensor: ")
print (r1)

r2 = torch.rand(2, 2)
print("\nA different random tensor: ")
print(r2) # new value

torch.manual_seed(1729)
r3 = torch.rand(2, 2)
print("\nThe same random tensor as before: ")
print(r3) # repeats tensor value

A random tensor: 
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor: 
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

The same random tensor as before: 
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


PyTorch tensors perform arithmetic operations intuitively. Tensors of similar shapes may be added, multiplied, etc. Operations with scalars are distributed over the tensor. 

In [5]:
ones = torch.ones(2,3)
print(ones)

twos = torch.ones(2,3) *2
print (twos)

threes = ones + twos
print(threes)
print(threes.shape)

r1=torch.rand(2,3)
r2=torch.rand(3,2)
r3=r1+r2
print(r3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

Here's a small sample of the mathematical operations available:

In [ ]:
r = (torch.rand(2,2) - 0.5) * 2
print ("A random tensor with values between -1 and 1: ")
print(r)

#Common mathematical operations
print ("\n absolute value of r:")
print (torch.abs(r))

# as trigonometric functions
print("\n inverse sine of r:")
print(torch.asin(r))

#...and linear algebra operations like determinants and singular value decomposition
print ("\n determinant of r:")
print (torch.det(r))
print ("\n singular value decomposition of r:")
print (torch.svd(r))

#...and statistical and aggregate operations
print("\naverage and standard deviation of r:")
print(torch.std_mean(r))
print("\nMaximum value of r:")
print(torch.max(r))

A random tensor with values between -1 and 1: 
tensor([[ 0.2987, -0.4734],
        [-0.0476, -0.8904]])

 absolute value of r:
tensor([[0.2987, 0.4734],
        [0.0476, 0.8904]])

 inverse sine of r:
tensor([[ 0.3033, -0.4931],
        [-0.0476, -1.0983]])

 determinant of r:
tensor(-0.2885)

 singular value decomposition of r:
torch.return_types.svd(
U=tensor([[ 0.4954,  0.8687],
        [ 0.8687, -0.4954]]),
S=tensor([1.0136, 0.2846]),
V=tensor([[ 0.1052,  0.9944],
        [-0.9944,  0.1052]]))

average and standard deviation of r:
(tensor(0.5160), tensor(-0.2782))

Maximum value of r:
tensor(0.2987)
