Creating tensors
Simples way is torch.empty() call

In [2]:
import torch
x = torch.empty(3,4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[-5.9493e+20,  7.6511e-43,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


- created a tensor using one of numerous facor methods
- tensor itself is 2d, having 3 rows 4 columns
- obj is tourch.Tensor, whith is alias for toch.FloatTensor; by default it's populated with 32-bit floating point
- see random-looking alues when printing your tensor, roch.empty() allocates memory for tensor, but does not initialize any values, so what is here is whatever was in memory
Brief note about tensors and number of dimensions and terminology
- see a 1d tensor called vector
- 2d tensor is a matrix
- Anything larget than 2d is just a tensor

More often than not, want to initialize tensor with some value, common cases all zeros, all ones, or random values, and the torch model provides factory methods for all of these

In [3]:
zeros=torch.zeros(2,3)
print(zeros)
ones=torch.ones(2,3)
print(ones)

torch.manual_seed(1729)
random=torch.rand(2,3)
print(random)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


The factor methods do all you'd expect we have a tensor full of zeros, another full of ones. Manual seed, you will reinitialize pseudo RNG and ge tthe same ones. 

In [4]:
torch.manual_seed(1729)
random1=torch.rand(2,3)
print(random1)

random2=torch.rand(2,3)
print(random2)

torch.manual_seed(1729)
random3=torch.rand(2,3)
print(random3)

random4=torch.rand(2,3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


random 1 and random 3 are the same, random 2 and random 4 are the sa,e. Manually setting RNG seed resets, so identical computation depnding on random number should in most cases provide identical results.

Tensor Shapes
Often when performing operations on two or more tensors, need to be same shape, having same number of dimensions and cells. For that we have torch.*_like() methods.

In [5]:
x=torch.empty(2,2,3)
print(x.shape)
print(x)

empty_like_x=torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x=torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x=torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x=torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


Last way to create a tensor that will cover is to specify its data direcly from a PyTorch collection:

In [7]:
some_constants=torch.tensor([[3.14159, 2.71828], [1.61803, 0.57721]])
print(some_constants)

some_integers=torch.tensor((2,3,5,7,11,13,17,19))
print(some_integers)

more_integers=torch.tensor(((2,4,6), [3,6,9]))
print(more_integers)


tensor([[3.1416, 2.7183],
        [1.6180, 0.5772]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


Using torch.tensor() is the most straightforward way to create a tensor if you already have data in python tuple or list. Nesting them creates multi-dimensional tensor

Note: torch.tensor() creates a copy of the data