Creating tensors
Simples way is torch.empty() call

In [13]:
import torch
x = torch.empty(3,4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0.0000, 2.8125, 0.0000, 2.8125],
        [0.0000, 2.8125, 0.0000, 2.8125],
        [0.0000, 2.8125, 0.0000, 2.8125]])


- created a tensor using one of numerous facor methods
- tensor itself is 2d, having 3 rows 4 columns
- obj is tourch.Tensor, whith is alias for toch.FloatTensor; by default it's populated with 32-bit floating point
- see random-looking alues when printing your tensor, roch.empty() allocates memory for tensor, but does not initialize any values, so what is here is whatever was in memory
Brief note about tensors and number of dimensions and terminology
- see a 1d tensor called vector
- 2d tensor is a matrix
- Anything larget than 2d is just a tensor

More often than not, want to initialize tensor with some value, common cases all zeros, all ones, or random values, and the torch model provides factory methods for all of these

In [14]:
zeros=torch.zeros(2,3)
print(zeros)
ones=torch.ones(2,3)
print(ones)

torch.manual_seed(1729)
random=torch.rand(2,3)
print(random)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


The factor methods do all you'd expect we have a tensor full of zeros, another full of ones. Manual seed, you will reinitialize pseudo RNG and ge tthe same ones. 

In [15]:
torch.manual_seed(1729)
random1=torch.rand(2,3)
print(random1)

random2=torch.rand(2,3)
print(random2)

torch.manual_seed(1729)
random3=torch.rand(2,3)
print(random3)

random4=torch.rand(2,3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


random 1 and random 3 are the same, random 2 and random 4 are the sa,e. Manually setting RNG seed resets, so identical computation depnding on random number should in most cases provide identical results.

Tensor Shapes
Often when performing operations on two or more tensors, need to be same shape, having same number of dimensions and cells. For that we have torch.*_like() methods.

In [16]:
x=torch.empty(2,2,3)
print(x.shape)
print(x)

empty_like_x=torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x=torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x=torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x=torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[1.4013e-45, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]],

        [[1.4013e-45, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[-0.0000e+00,  1.6082e+00,  2.0000e+00],
         [ 1.7023e+00, -0.0000e+00,  1.5912e+00]],

        [[ 3.6893e+19,  1.8732e+00, -2.0000e+00],
         [ 1.7064e+00,  1.0842e-19,  1.7735e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


Last way to create a tensor that will cover is to specify its data direcly from a PyTorch collection:

In [17]:
some_constants=torch.tensor([[3.14159, 2.71828], [1.61803, 0.57721]])
print(some_constants)

some_integers=torch.tensor((2,3,5,7,11,13,17,19))
print(some_integers)

more_integers=torch.tensor(((2,4,6), [3,6,9]))
print(more_integers)


tensor([[3.1416, 2.7183],
        [1.6180, 0.5772]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


Using torch.tensor() is the most straightforward way to create a tensor if you already have data in python tuple or list. Nesting them creates multi-dimensional tensor

Note: torch.tensor() creates a copy of the data

Tensor Data Types

In [18]:
import torch
a = torch.ones((2,3), dtype=torch.int16)
print(a)

b=torch.ones((2,3), dtype=torch.float64)*20.
print(b)

c=b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[20., 20., 20.],
        [20., 20., 20.]], dtype=torch.float64)
tensor([[20, 20, 20],
        [20, 20, 20]], dtype=torch.int32)


simplest way to set tensor is with an optional argument at creation time. In the first line of the cell above, we set dtype=torch.init16 for the tensor a. We print a, it's full of 1 rather than 1. subtle cue that it's an integer type. printing the tensor also specifies dtype at a. 

Specifying tensor shape as series of arguments, we group those elements to a tuple. This is not necessary as Pytorch will take initial unlabeled integer arguments as tensor shape. when adding optional argument, it can make intent more readable. 

other way to set the datatype is with the .to() method. we call a random floating tensor b the usual way, following we create c from b with that conversion.

Can use 
bool
int8
uint8
int16
int32
int64
half
float
double
bfloat


Math & Logic with PyTorch Tensors
Now that you know some of the ways to create a tensor, what can you do with them?

Basic arithmetic with scalars


In [19]:
ones=torch.zeros(2,2)+1
twos=torch.ones(2,2)*2
threes=(torch.ones(2,2)*7-1)/2
fours=twos**2;
sqrt2s=twos**0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


Applies to every single one, addition multiplication division exponentiation distributed over every element. Output of such an operation will be tensor, you can chain them together with the usual operator precedence rule.

Simlar operations between 2 tensors behave like you'd intuitively expect:


In [20]:
powers2=twos**torch.tensor([[1,2],[3,4]])
print(powers2)
fives=ones+fours
print(fives)
dozens=threes*fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


cannot operate on tensors different shapes except for one exception. 

In [21]:
rand=torch.rand(2,4)
doubled=torch.rand(2,4)*(torch.ones(1,4)*2)
print(rand)
print(doubled)

tensor([[0.5062, 0.8469, 0.2588, 0.2707],
        [0.4115, 0.6839, 0.0703, 0.5105]])
tensor([[1.8901, 0.4717, 0.3959, 0.6655],
        [1.2291, 1.1998, 1.0026, 1.8793]])


Broadcasting is a way to perform an operation between tensors that have similarities in shapes. The one-row, four-column tensor is multiplied by both rows of the two-row, four column tensor. 

Way to perform operations with similarities in shapes. the one-row four column tensor is multiplied by both rows of the two-row four column tensor

This is important operation in deep learning. Multiplying a tensor of learning weights by a batch of input tensors, applying the operation to each instance in the batch seperately, and returning a tensor of identical shape. 

Rules for braodcasting are:
- Each tensor has at least one dimension
- comparing the dimension sizes of the two tensors going from last to first
- each dimension must be equal, or
- one of the dimensions must be of size 1, or
- the dimension does not exist in one of the tensors
tensors of identical shape are trivially broadcastable

In [22]:
a= torch.ones(4,3,2)
b=a*(torch.rand(    3,2))
print(b)
c=a * torch.rand(   3,1)
print(c)
d=a*torch.rand(    1,2)
print(d)    

tensor([[[0.8656, 0.5207],
         [0.6865, 0.3614],
         [0.6493, 0.2633]],

        [[0.8656, 0.5207],
         [0.6865, 0.3614],
         [0.6493, 0.2633]],

        [[0.8656, 0.5207],
         [0.6865, 0.3614],
         [0.6493, 0.2633]],

        [[0.8656, 0.5207],
         [0.6865, 0.3614],
         [0.6493, 0.2633]]])
tensor([[[0.4762, 0.4762],
         [0.0548, 0.0548],
         [0.2024, 0.2024]],

        [[0.4762, 0.4762],
         [0.0548, 0.0548],
         [0.2024, 0.2024]],

        [[0.4762, 0.4762],
         [0.0548, 0.0548],
         [0.2024, 0.2024]],

        [[0.4762, 0.4762],
         [0.0548, 0.0548],
         [0.2024, 0.2024]]])
tensor([[[0.5731, 0.7191],
         [0.5731, 0.7191],
         [0.5731, 0.7191]],

        [[0.5731, 0.7191],
         [0.5731, 0.7191],
         [0.5731, 0.7191]],

        [[0.5731, 0.7191],
         [0.5731, 0.7191],
         [0.5731, 0.7191]],

        [[0.5731, 0.7191],
         [0.5731, 0.7191],
         [0.5731, 0.7191]]])


Look closely at the values of each tensor above:
-multplication that created b was broadcast over every layer of a
-for c operation braodcast over every layer and row of a
-for d switch around, every row identical across layers and columns.

Here are examples of broadcasting that will fail:

In [23]:
a=torch.ones(4,3,2) 
b=a*torch.rand(4,3) #dimensions must match last to first
c=a*torch.rand(2,3) # both 2nd and 3rd dimensions are different
d=a*torch.rand((0,)) # can't broadcast with an empty tensor

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

More Math with Tensors
common functions: .abs, .ceil, .floor, .clamp

Trigonometric functions: .sin, .asin, math.pi

Bitwise operations: .bitwise_xor

Comparisons: .eq

Reductions: .max --> single element tensor .mean, .std, .prod, .unique, filter unique elements

vector operations: torch.cross, .matmul, matrix multiplication


Altering Tensors in place:

Most binary operations on tensors will return a third new tensor. new tensor c will occupy region of memory distinc. 

There are times may with to alter tensor in place. Most math funcitons have a version with appended underscore (_) that will alter a tensor in place

In [ ]:
import math
a = torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])
print('a:')
print(a)
print(torch.sin(a))
print(a)

b = torch.tensor([0, math.pi/4, math.pi/2, 3*math.pi/4])
print('\nb:')
print(b)
print(torch.sin_(b)) # b has changed
print(b) 

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


Arithmetic operations, there are functions that behave similarly:

In [ ]:
a=torch.ones(2,2)
b=torch.rand(2,2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying:')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.8366, 0.4992],
        [0.7505, 0.7500]])

After adding:
tensor([[1.8366, 1.4992],
        [1.7505, 1.7500]])
tensor([[1.8366, 1.4992],
        [1.7505, 1.7500]])
tensor([[0.8366, 0.4992],
        [0.7505, 0.7500]])

After multiplying:
tensor([[0.6999, 0.2492],
        [0.5632, 0.5625]])
tensor([[0.6999, 0.2492],
        [0.5632, 0.5625]])


Note that these in-place arithmetic functions are methods on the torch.Tensor object, not attached to the torch module like many other functions, eg torch.sin(). As you can see from a.add_(b), the calling tensor is the one that gets changed in place. 

There is another option for placing the result of a computation in an existing allocated tensor. Many of the functions and methods we've seen before have out argument that lets you specify tensor recieve the output if the out tensor is the correct shape and dtype. This can happen without a new memory allocation:

In [ ]:
a=torch.rand(2,2)
b=torch.rand(2,2)
c=torch.zeros(2,2)
old_id=id(c)

print(c)
d=torch.matmul(a,b,out=c)
print(c)

assert c is d
assert id(c), old_id

torch.rand(2, 2, out=c)
print(c)
assert id(c), old_id

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.8359, 0.7033],
        [0.9176, 0.5511]])
tensor([[0.9945, 0.6080],
        [0.8496, 0.4122]])


Copying Tensors
As with any object in python,  assigning a tensor to a varialbe makes the variable a label of the tensor, it does not copy it.

In [ ]:
a=torch.ones(2,2)
b=a

a[0][1]=561
print(b)

tensor([[  1., 561.],
        [  1.,   1.]])


But what if you want a seperate copy of the data to work on? The clone() method is there for you:

In [ ]:
a=torch.ones(2,2)
b=a.clone()

assert b is not a
print(torch.eq(a,b))

a[0][1]=561
print(b)

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


THere is an important thing to note when using clone(). If your source tensor has autograd enabled, then so will the clone.

Many cases, this is what you want. For example,multiple computation paths in its forward() method, and both the original tensor and its clone contribute to model output. THen to enable model learning, you want autograd turned on for both tensors. Source autograd enabled, get the result you want.

If you have a computation where neither og or clone need graidents, as long as source autograd off, good to go.

Third case: Image performing computation in forward() funciton, graidents are turned on for everything by default. want to pull some values mid stream to generate some metrics. Don't want the cloned copy of source tensor to track gradient. Performance is improved with autograd's history tracking turned off. Can use .detach() method on the source tensor:

In [ ]:
a=torch.rand(2,2,requires_grad=True)
print(a)

b=a.clone()
print(b)

c=a.detach().clone()
print(c)

print(a)

tensor([[0.4822, 0.8173],
        [0.2182, 0.4697]], requires_grad=True)
tensor([[0.4822, 0.8173],
        [0.2182, 0.4697]], grad_fn=<CloneBackward0>)
tensor([[0.4822, 0.8173],
        [0.2182, 0.4697]])
tensor([[0.4822, 0.8173],
        [0.2182, 0.4697]], requires_grad=True)


What's happening here?

Create a with requires_grad=true turned on. Haven't covered this optional argument yet. will during unit on autograd
print a, informs us requires_grad=True
we clone a label it b, see track computation history, inherited a autograd
clone a into c but detach it first
printing see, no computation history

Moving to GPU

One of the major advantages of PyTorch is its robust acceleration on CUDA-compadible Nvidia GPU. ("CUDA" stands for Compute Unified Device Architecture)Everything we've done has been on CPU. How do we move to that?

First we check whether a GPU is available with the is_available() method.

Note: If you do not have a CUDA-compatible GPU and CUDA drivers installed, the executable cells in this section will not execute any GPU-related code.

In [ ]:
if torch.cuda.is_available():
    print("We have a GPU!")
else:
    print("No GPU available, sorry :(")

No GPU available, sorry :(


Once we've determined one or more GPUs available, need someplace where GPU can see it. CPU does comutation on data in your computer's RAM. GPU has dedicated memory attached to it. Want to perform a computation on a device, must move all the data needed for computaiton to memory accessible by that device. 

Multiple ways to get your data onto target device. May do it at creation time.

In [ ]:
if torch.cuda.is_available():
    gpu_rand=torch.rand(2,2,device="cuda")
    print(gpu_rand)
else:
    print("No GPU available, sorry :(")

No GPU available, sorry :(


By default, new tensors are created on the CPU so we have to specify if we want to create tensor on GPU with optional device argument. See when we print the new tensor, PyTorch informs what device it's on if not CPU. 

Query # of GPUs with torch.cuda.device_count(). If you have more than one GPU, specify them by index. device='cuda:0' device='cuda:1' etc

As coding practice, specifying our degive everywhere with string contants is fragile. Ideal world, perform robustly whether on CPU or GPU hardware. Do this by creating a device handle that can be passed to tensors instead of a string:

In [ ]:
if torch.cuda.is_available():
    my_device = torch.device("cuda")
else:
    my_device = torch.device("cpu")
print("Device:{}".format(my_device))

x=torch.rand(2,2,device=my_device)
print(x)

Device:cpu
tensor([[0.5059, 0.8841],
        [0.6228, 0.6416]])


If you have an existing tensor living on one device, you can move it to another with the to() method. The following line of code creates a tensor on CPI, and moves it to whichever device handle you aquired in the previous cell. 

In [ ]:
y=torch.rand(2,2)
y=y.to(my_device)

NameError: name 'my_device' is not defined

It is important to know that in order to do computation involving two or more tensors, all tensors must be on the same device. The following code will throw runtime error regardles of GPU device availability:

x=torch.rand(2,2)
y=torch.rand(2,2, device="gpu")
z=x+y

Manipulating Tensor Shapes:
Sometimes, you'll need to change the shape of your tensor. Blow we'll look at a few common cases and how to handle the,.

Changing the number of dimensions:
One case where you need change # of dimensions is single instance of input to your model. PyTorch models generally expect batches of input.

For example, imaging having a model that works on (3,226,226). Model expecting (N,3,226,226), where N is the number of images in the batch. So how do you make a batch of one?

In [24]:
a = torch.rand(3,226,226)
b=a.unsqueeze(0)
print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


The unsqueeze() method adds a dimension of extent 1, unsqueeze(0) adds it as a new zeroth dimension, now you have a batch of one!

Unsqueezing, what do we mean by squeezing? We're taking advantage of the fact that any dimension of extent 1 does not change the number of elements in tensor.

In [25]:
c=torch.rand(1,1,1,1,1)
print(c)

tensor([[[[[0.5258]]]]])


continuing the example above, let's say the model's output is a 20-element vector for each input. You would then expect the output to have shape (N,20). where N is the number of instancs in the input batch. That means that for our single-input batch, we'll get an output of shape (1,20).

What if you want to do some non-batched computation with that ouput - something that's just expecting a 20-element vector?

In [26]:
a = torch.rand(1,20)
print(a.shape)
print(a)

b=a.squeeze(0)
print(b.shape)
print(b)

c=torch.rand(2,2)
print(c.shape)

d=c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[5.3291e-01, 5.8985e-01, 4.9331e-01, 3.6653e-01, 1.8910e-01, 9.7746e-01,
         7.7808e-01, 9.1508e-02, 4.6269e-01, 7.9468e-01, 7.4779e-01, 8.8274e-01,
         6.3341e-01, 3.9022e-01, 3.6907e-01, 7.1114e-04, 4.4247e-01, 2.2991e-01,
         5.2522e-01, 9.4127e-01]])
torch.Size([20])
tensor([5.3291e-01, 5.8985e-01, 4.9331e-01, 3.6653e-01, 1.8910e-01, 9.7746e-01,
        7.7808e-01, 9.1508e-02, 4.6269e-01, 7.9468e-01, 7.4779e-01, 8.8274e-01,
        6.3341e-01, 3.9022e-01, 3.6907e-01, 7.1114e-04, 4.4247e-01, 2.2991e-01,
        5.2522e-01, 9.4127e-01])
torch.Size([2, 2])
torch.Size([2, 2])


You can see from the shapes that our 2-dimension tensor is now 1-dimensional, and if you look closely at output of cell, a shows extra set of square brackets [] from extra dimension. Only squeeze() dimensions of extent 1. Squeeze and unsqueeze can only act on dimensions of extent 1, or else if would change # of elements in tensor. 

Another place you use unsqueeze() is ease broadcasting. Recall the example above when we had the following code:
a=torch.ones(4,3,2)
c=a*torch.rand( 3,1) #3rd dim-1, 2nd dim identical to a print(c)

The net effect of that was to broadcast operation over dimensions 0 and 2, causing random 3x1 tensor to be multiplied element-wise by every 3-elemt of column a.

Random element was just 3 element vector, lose ability to broadcast, because the final dimensions would not match up according to the broadcasting rules. unsqueeze() comes to the rescue. 

In [27]:
a=torch.ones(4,3,2)
b=torch.rand(3)
c=b.unsqueeze(1)
print(c.shape)
print(a*c)

torch.Size([3, 1])
tensor([[[0.1448, 0.1448],
         [0.5758, 0.5758],
         [0.8992, 0.8992]],

        [[0.1448, 0.1448],
         [0.5758, 0.5758],
         [0.8992, 0.8992]],

        [[0.1448, 0.1448],
         [0.5758, 0.5758],
         [0.8992, 0.8992]],

        [[0.1448, 0.1448],
         [0.5758, 0.5758],
         [0.8992, 0.8992]]])


squeeze() and unsqueeze() methods also have in-place versions, squeeze_() and unsqueeze()

In [28]:
batch_me=torch.rand(3,226,226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)


torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


Sometimes, need to change shape of tensor more radically, while still preserving elements and their contents. One case where this happens is at the interface between a convolutional layer of a model and a linera layer of the model - this is common in image classification models. A convolution kernal will yield an output tensor of shape features x width x height, but the following linear layer expects 1-d input. The reshape() will do this for you, provided that the dimensions you request yield the same number of elements as the input tensor has:

In [30]:
output3d=torch.rand(6,20,20)
print(output3d.shape)

input1d=output3d.reshape(6*20*20)
print(input1d.shape)

#can also call it as a method on the torch module:
print(torch.reshape(output3d, (6*20*20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


The (6*20*20,) argument in the final line of the cell aboe is because PyTorch expects a tuple when specifying a tensor shape - but when the shape is the first argument of a method, it lets us cheat and just use a series of integers. Here, we had to add parentheses and comma to convince the method that this is really a one-element tuple.

When it can, reshape() will return a view on the tensor to be changed, that is a seperate tensor object looking at the same underlying region of memory. Means any change made to source tnesor reflect in the view on that tensor, unless you clone() it. 

NumPy Bridge
PyTorch Broadcast semantics are compatible with NumPysm but relation is deper than that.

If you have existing ML or scientific code with data stored in NumPy ndarrays, you may wish to express that same data as PyTorch tensors, whether to take advantage of PyTorch's GPU acceleration, or its efficient abstractions for building ML models. It's easy to switch between ndarrays and PyTorch tensors:


In [31]:
import numpy as np

numpy_array=np.ones((2,3))
print(numpy_array)

pytorch_tensor=torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


PyTorch creates a tensor of the same shape containign the same data as the NumPy array, going as far to keep NumPy default 64-bit data type. Conversion can go the other way. 

In [32]:
pytorch_rand=torch.rand(2,3)
print(pytorch_rand)

numpy_rand=pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.9734, 0.3484, 0.2205],
        [0.7693, 0.2605, 0.4367]])
[[0.9733666  0.34842658 0.22047472]
 [0.76926184 0.26052505 0.43671775]]


It is important to know these converted objects are using the same underlying memory as their source objects. meaning changes in one are reflected in the other. 

In [33]:
numpy_array[1,1]=23
print(pytorch_tensor)

pytorch_rand[1,1]=17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.9733666   0.34842658  0.22047472]
 [ 0.76926184 17.          0.43671775]]
