Creating tensors
Simples way is torch.empty() call

In [2]:
import torch
x = torch.empty(3,4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[-5.9493e+20,  7.6511e-43,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


- created a tensor using one of numerous facor methods
- tensor itself is 2d, having 3 rows 4 columns
- obj is tourch.Tensor, whith is alias for toch.FloatTensor; by default it's populated with 32-bit floating point
- see random-looking alues when printing your tensor, roch.empty() allocates memory for tensor, but does not initialize any values, so what is here is whatever was in memory
Brief note about tensors and number of dimensions and terminology
- see a 1d tensor called vector
- 2d tensor is a matrix
- Anything larget than 2d is just a tensor

More often than not, want to initialize tensor with some value, common cases all zeros, all ones, or random values, and the torch model provides factory methods for all of these

In [3]:
zeros=torch.zeros(2,3)
print(zeros)
ones=torch.ones(2,3)
print(ones)

torch.manual_seed(1729)
random=torch.rand(2,3)
print(random)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


The factor methods do all you'd expect we have a tensor full of zeros, another full of ones. Manual seed, you will reinitialize pseudo RNG and ge tthe same ones. 

In [4]:
torch.manual_seed(1729)
random1=torch.rand(2,3)
print(random1)

random2=torch.rand(2,3)
print(random2)

torch.manual_seed(1729)
random3=torch.rand(2,3)
print(random3)

random4=torch.rand(2,3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


random 1 and random 3 are the same, random 2 and random 4 are the sa,e. Manually setting RNG seed resets, so identical computation depnding on random number should in most cases provide identical results.

Tensor Shapes
Often when performing operations on two or more tensors, need to be same shape, having same number of dimensions and cells. For that we have torch.*_like() methods.

In [5]:
x=torch.empty(2,2,3)
print(x.shape)
print(x)

empty_like_x=torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x=torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x=torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x=torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


Last way to create a tensor that will cover is to specify its data direcly from a PyTorch collection:

In [7]:
some_constants=torch.tensor([[3.14159, 2.71828], [1.61803, 0.57721]])
print(some_constants)

some_integers=torch.tensor((2,3,5,7,11,13,17,19))
print(some_integers)

more_integers=torch.tensor(((2,4,6), [3,6,9]))
print(more_integers)


tensor([[3.1416, 2.7183],
        [1.6180, 0.5772]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


Using torch.tensor() is the most straightforward way to create a tensor if you already have data in python tuple or list. Nesting them creates multi-dimensional tensor

Note: torch.tensor() creates a copy of the data

Tensor Data Types

In [2]:
import torch
a = torch.ones((2,3), dtype=torch.int16)
print(a)

b=torch.ones((2,3), dtype=torch.float64)*20.
print(b)

c=b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[20., 20., 20.],
        [20., 20., 20.]], dtype=torch.float64)
tensor([[20, 20, 20],
        [20, 20, 20]], dtype=torch.int32)


simplest way to set tensor is with an optional argument at creation time. In the first line of the cell above, we set dtype=torch.init16 for the tensor a. We print a, it's full of 1 rather than 1. subtle cue that it's an integer type. printing the tensor also specifies dtype at a. 

Specifying tensor shape as series of arguments, we group those elements to a tuple. This is not necessary as Pytorch will take initial unlabeled integer arguments as tensor shape. when adding optional argument, it can make intent more readable. 

other way to set the datatype is with the .to() method. we call a random floating tensor b the usual way, following we create c from b with that conversion.

Can use 
bool
int8
uint8
int16
int32
int64
half
float
double
bfloat


Math & Logic with PyTorch Tensors
Now that you know some of the ways to create a tensor, what can you do with them?

Basic arithmetic with scalars


In [3]:
ones=torch.zeros(2,2)+1
twos=torch.ones(2,2)*2
threes=(torch.ones(2,2)*7-1)/2
fours=twos**2;
sqrt2s=twos**0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


Applies to every single one, addition multiplication division exponentiation distributed over every element. Output of such an operation will be tensor, you can chain them together with the usual operator precedence rule.

Simlar operations between 2 tensors behave like you'd intuitively expect:


In [6]:
powers2=twos**torch.tensor([[1,2],[3,4]])
print(powers2)
fives=ones+fours
print(fives)
dozens=threes*fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


cannot operate on tensors different shapes except for one exception. 

In [7]:
rand=torch.rand(2,4)
doubled=torch.rand(2,4)*(torch.ones(1,4)*2)
print(rand)
print(doubled)

tensor([[0.9853, 0.8872, 0.4359, 0.3674],
        [0.0530, 0.1565, 0.5807, 0.1950]])
tensor([[1.7438, 0.9186, 1.5956, 0.4300],
        [0.7948, 0.2661, 0.2184, 1.5024]])


Broadcasting is a way to perform an operation between tensors that have similarities in shapes. The one-row, four-column tensor is multiplied by both rows of the two-row, four column tensor. 

Way to perform operations with similarities in shapes. the one-row four column tensor is multiplied by both rows of the two-row four column tensor

This is important operation in deep learning. Multiplying a tensor of learning weights by a batch of input tensors, applying the operation to each instance in the batch seperately, and returning a tensor of identical shape. 

Rules for braodcasting are:
- Each tensor has at least one dimension
- comparing the dimension sizes of the two tensors going from last to first
- each dimension must be equal, or
- one of the dimensions must be of size 1, or
- the dimension does not exist in one of the tensors
tensors of identical shape are trivially broadcastable

In [8]:
a= torch.ones(4,3,2)
b=a*(torch.rand(    3,2))
print(b)
c=a * torch.rand(   3,1)
print(c)
d=a*torch.rand(    1,2)
print(d)    

tensor([[[0.9706, 0.5124],
         [0.6824, 0.0316],
         [0.9313, 0.7652]],

        [[0.9706, 0.5124],
         [0.6824, 0.0316],
         [0.9313, 0.7652]],

        [[0.9706, 0.5124],
         [0.6824, 0.0316],
         [0.9313, 0.7652]],

        [[0.9706, 0.5124],
         [0.6824, 0.0316],
         [0.9313, 0.7652]]])
tensor([[[0.6160, 0.6160],
         [0.3957, 0.3957],
         [0.5293, 0.5293]],

        [[0.6160, 0.6160],
         [0.3957, 0.3957],
         [0.5293, 0.5293]],

        [[0.6160, 0.6160],
         [0.3957, 0.3957],
         [0.5293, 0.5293]],

        [[0.6160, 0.6160],
         [0.3957, 0.3957],
         [0.5293, 0.5293]]])
tensor([[[0.9624, 0.4855],
         [0.9624, 0.4855],
         [0.9624, 0.4855]],

        [[0.9624, 0.4855],
         [0.9624, 0.4855],
         [0.9624, 0.4855]],

        [[0.9624, 0.4855],
         [0.9624, 0.4855],
         [0.9624, 0.4855]],

        [[0.9624, 0.4855],
         [0.9624, 0.4855],
         [0.9624, 0.4855]]])


Look closely at the values of each tensor above:
-multplication that created b was broadcast over every layer of a
-for c operation braodcast over every layer and row of a
-for d switch around, every row identical across layers and columns.

Here are examples of broadcasting that will fail: